In [ ]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import models, layers, optimizers, callbacks, applications

In [ ]:
# get the image data
(X_train, y_train), (X_test, y_test) = keras.datasets.cifar100.load_data()

In [ ]:
X_train[0]

array([[[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [195, 205, 193],
        [212, 224, 204],
        [182, 194, 167]],

       [[255, 255, 255],
        [254, 254, 254],
        [254, 254, 254],
        ...,
        [170, 176, 150],
        [161, 168, 130],
        [146, 154, 113]],

       [[255, 255, 255],
        [254, 254, 254],
        [255, 255, 255],
        ...,
        [189, 199, 169],
        [166, 178, 130],
        [121, 133,  87]],

       ...,

       [[148, 185,  79],
        [142, 182,  57],
        [140, 179,  60],
        ...,
        [ 30,  17,   1],
        [ 65,  62,  15],
        [ 76,  77,  20]],

       [[122, 157,  66],
        [120, 155,  58],
        [126, 160,  71],
        ...,
        [ 22,  16,   3],
        [ 97, 112,  56],
        [141, 161,  87]],

       [[ 87, 122,  41],
        [ 88, 122,  39],
        [101, 134,  56],
        ...,
        [ 34,  36,  10],
        [105, 133,  59],
        [138, 173,  79]]

In [ ]:
# look at what the outcome variable looks like
y_train[:10]

array([[19],
       [29],
       [ 0],
       [11],
       [ 1],
       [86],
       [90],
       [28],
       [23],
       [31]])

In [ ]:
# check the number of classes
np.unique(y_train)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [ ]:
# check the count of each class in the training set
unique, counts = np.unique(y_train, return_counts=True)
print(np.asarray((unique, counts)).T)

[[  0 500]
 [  1 500]
 [  2 500]
 [  3 500]
 [  4 500]
 [  5 500]
 [  6 500]
 [  7 500]
 [  8 500]
 [  9 500]
 [ 10 500]
 [ 11 500]
 [ 12 500]
 [ 13 500]
 [ 14 500]
 [ 15 500]
 [ 16 500]
 [ 17 500]
 [ 18 500]
 [ 19 500]
 [ 20 500]
 [ 21 500]
 [ 22 500]
 [ 23 500]
 [ 24 500]
 [ 25 500]
 [ 26 500]
 [ 27 500]
 [ 28 500]
 [ 29 500]
 [ 30 500]
 [ 31 500]
 [ 32 500]
 [ 33 500]
 [ 34 500]
 [ 35 500]
 [ 36 500]
 [ 37 500]
 [ 38 500]
 [ 39 500]
 [ 40 500]
 [ 41 500]
 [ 42 500]
 [ 43 500]
 [ 44 500]
 [ 45 500]
 [ 46 500]
 [ 47 500]
 [ 48 500]
 [ 49 500]
 [ 50 500]
 [ 51 500]
 [ 52 500]
 [ 53 500]
 [ 54 500]
 [ 55 500]
 [ 56 500]
 [ 57 500]
 [ 58 500]
 [ 59 500]
 [ 60 500]
 [ 61 500]
 [ 62 500]
 [ 63 500]
 [ 64 500]
 [ 65 500]
 [ 66 500]
 [ 67 500]
 [ 68 500]
 [ 69 500]
 [ 70 500]
 [ 71 500]
 [ 72 500]
 [ 73 500]
 [ 74 500]
 [ 75 500]
 [ 76 500]
 [ 77 500]
 [ 78 500]
 [ 79 500]
 [ 80 500]
 [ 81 500]
 [ 82 500]
 [ 83 500]
 [ 84 500]
 [ 85 500]
 [ 86 500]
 [ 87 500]
 [ 88 500]
 [ 89 500]
 [ 90 500]

In [ ]:
# check the count of each class in the testing set
unique, counts = np.unique(y_test, return_counts=True)
print(np.asarray((unique, counts)).T)

[[  0 100]
 [  1 100]
 [  2 100]
 [  3 100]
 [  4 100]
 [  5 100]
 [  6 100]
 [  7 100]
 [  8 100]
 [  9 100]
 [ 10 100]
 [ 11 100]
 [ 12 100]
 [ 13 100]
 [ 14 100]
 [ 15 100]
 [ 16 100]
 [ 17 100]
 [ 18 100]
 [ 19 100]
 [ 20 100]
 [ 21 100]
 [ 22 100]
 [ 23 100]
 [ 24 100]
 [ 25 100]
 [ 26 100]
 [ 27 100]
 [ 28 100]
 [ 29 100]
 [ 30 100]
 [ 31 100]
 [ 32 100]
 [ 33 100]
 [ 34 100]
 [ 35 100]
 [ 36 100]
 [ 37 100]
 [ 38 100]
 [ 39 100]
 [ 40 100]
 [ 41 100]
 [ 42 100]
 [ 43 100]
 [ 44 100]
 [ 45 100]
 [ 46 100]
 [ 47 100]
 [ 48 100]
 [ 49 100]
 [ 50 100]
 [ 51 100]
 [ 52 100]
 [ 53 100]
 [ 54 100]
 [ 55 100]
 [ 56 100]
 [ 57 100]
 [ 58 100]
 [ 59 100]
 [ 60 100]
 [ 61 100]
 [ 62 100]
 [ 63 100]
 [ 64 100]
 [ 65 100]
 [ 66 100]
 [ 67 100]
 [ 68 100]
 [ 69 100]
 [ 70 100]
 [ 71 100]
 [ 72 100]
 [ 73 100]
 [ 74 100]
 [ 75 100]
 [ 76 100]
 [ 77 100]
 [ 78 100]
 [ 79 100]
 [ 80 100]
 [ 81 100]
 [ 82 100]
 [ 83 100]
 [ 84 100]
 [ 85 100]
 [ 86 100]
 [ 87 100]
 [ 88 100]
 [ 89 100]
 [ 90 100]

In [ ]:
# check the shape of data
print((X_train.shape, y_train.shape))
print((X_test.shape, y_test.shape))

((50000, 32, 32, 3), (50000, 1))
((10000, 32, 32, 3), (10000, 1))


In [ ]:
# one hot encode the outcome variable
y_train = keras.utils.to_categorical(y_train, len(np.unique(y_train)))
y_test = keras.utils.to_categorical(y_test, len(np.unique(y_test)))

y_train

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [ ]:
# check the shape of one hot encoded outcome variable
y_train.shape

(50000, 100)

In [ ]:
X_train = applications.resnet50.preprocess_input(X_train)
X_test = applications.resnet50.preprocess_input(X_test)

In [ ]:
input_tensor = keras.Input(shape=X_train.shape[1:len(X_train.shape)])
input_tensor

<KerasTensor: shape=(None, 32, 32, 3) dtype=float32 (created by layer 'input_1')>

In [ ]:
input_shape = X_train.shape[1:len(X_train.shape)]
input_shape

(32, 32, 3)

In [ ]:
# load the resnet50 model without the output layer
resnet50 = keras.applications.ResNet50(
    include_top=False,
    weights="imagenet",
    #input_tensor=input_tensor,
    input_shape=(224, 224, 3),
#    input_shape=input_shape,
)

In [ ]:
# freeze all the layers of the model
#for layer in resnet50.layers[:143]:
#  layer.trainable = False

for layer in resnet50.layers:
    if isinstance(layer, layers.BatchNormalization):
        layer.trainable = True
    else:
        layer.trainable = False

In [ ]:
# get the number of classes to pass to the output layer
n_classes = y_train.shape[1]
n_classes

100

In [ ]:
to_res = (224, 224)

model = models.Sequential([
    layers.Lambda(lambda image: tf.image.resize(image, to_res)),
    resnet50,
    layers.GlobalAveragePooling2D(),
    layers.Dense(256, activation='relu'),
    layers.Dropout(.25),
    layers.BatchNormalization(),
    layers.Dense(n_classes, activation='softmax')
])

In [ ]:
# compile the model
model.compile(optimizer='rmsprop', loss='categorical_crossentropy', metrics = ['accuracy'])

In [ ]:
# train the model on the data
history = model.fit(X_train, y_train, epochs=5, validation_data=[X_test, y_test], verbose=1, batch_size=64)

Epoch 1/5
782/782 [==============================] - 775s 962ms/step - loss: 1.5858 - accuracy: 0.5848 - val_loss: 0.9156 - val_accuracy: 0.7283
Epoch 2/5
782/782 [==============================] - 749s 958ms/step - loss: 0.8604 - accuracy: 0.7474 - val_loss: 0.7705 - val_accuracy: 0.7710
Epoch 3/5
782/782 [==============================] - 749s 959ms/step - loss: 0.6952 - accuracy: 0.7914 - val_loss: 0.7265 - val_accuracy: 0.7818
Epoch 4/5
782/782 [==============================] - 750s 959ms/step - loss: 0.5889 - accuracy: 0.8202 - val_loss: 0.7382 - val_accuracy: 0.7870
Epoch 5/5
782/782 [==============================] - 752s 961ms/step - loss: 0.5146 - accuracy: 0.8408 - val_loss: 0.7238 - val_accuracy: 0.7924


In [ ]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 lambda (Lambda)             (None, 224, 224, 3)       0         
                                                                 
 resnet50 (Functional)       (None, 7, 7, 2048)        23587712  
                                                                 
 global_average_pooling2d (G  (None, 2048)             0         
 lobalAveragePooling2D)                                          
                                                                 
 dense (Dense)               (None, 256)               524544    
                                                                 
 dropout (Dropout)           (None, 256)               0         
                                                                 
 batch_normalization (BatchN  (None, 256)              1024      
 ormalization)                                          

In [ ]:
model.save('my_model1')

INFO:tensorflow:Assets written to: my_model1/assets


/usr/local/lib/python3.7/dist-packages/keras/engine/functional.py:1410: CustomMaskWarning: Custom mask layers require a config and must override get_config. When loading, the custom mask layer must be passed to the custom_objects argument.
  layer_config = serialize_layer_fn(layer)
/usr/local/lib/python3.7/dist-packages/keras/saving/saved_model/layer_serialization.py:112: CustomMaskWarning: Custom mask layers require a config and must override get_config. When loading, the custom mask layer must be passed to the custom_objects argument.
  return generic_utils.serialize_keras_object(obj)
